type: object
additionalProperties: false
properties:
  id: { type: integer, format: int64, example: 1 }
  parent_id: { type: integer, format: int64, nullable: true, example: 10 }
  sku: { type: string, nullable: true, example: "SKU-CH-001" }
  name: { type: string, example: "Child Product 1" }
  is_active: { type: boolean, example: true }
  created_at: { type: string, format: date-time, example: "2026-02-11T08:00:00Z" }
  updated_at: { type: string, format: date-time, example: "2026-02-11T08:00:00Z" }
required: [id, name, is_active, created_at, updated_at]