type: object
additionalProperties: false
properties:
  id: { type: integer, format: int64, example: 10 }
  title: { type: string, example: "Product Child A" }
  description: { type: string, nullable: true, example: null }

  image:
    type: object
    additionalProperties: false
    properties:
      thumb: { type: string, nullable: true, example: null }
      normal: { type: string, nullable: true, example: null }
    required: [thumb, normal]

  measurment: { type: string, nullable: true, example: "Τεμάχιο" }
  cost: { type: number, nullable: true, example: 10 }
  sell_price: { type: number, nullable: true, example: 15 }
  website_price: { type: number, nullable: true, example: 15 }
  retail_price: { type: number, nullable: true, example: 20 }
  discounted_price: { type: number, nullable: true, example: 0 }
  builded_price: { type: number, nullable: true, example: 0 }

  tax:
    description: Tax value (e.g. 24) from related tax.
    type: number
    nullable: true
    example: 24

  stock:
    description: Either full stock (number/object) or partial stock depending on `stock` query param.
    nullable: true
    oneOf:
      - type: number
        example: 5
      - type: object
        additionalProperties: true

  barcode: { type: string, nullable: true, example: "5200000000000" }
  catalog_code: { type: string, nullable: true, example: "CAT-01" }
  erp_code: { type: string, nullable: true, example: "ERP-01" }

  product_id: { type: integer, format: int64, nullable: true, example: 100 }
  group_id: { type: integer, format: int64, nullable: true, example: 5 }
  parent_name: { type: string, nullable: true, example: "Parent Product" }

  company: { type: integer, format: int64, example: 1 }
  created: { type: string, example: "2026-02-11 10:00:00" }
  updated: { type: string, example: "2026-02-11 10:00:00" }

  characteristicsHtml:
    type: string
    nullable: true
    description: HTML string generated by backend.
    example: "<span>...</span>"

  characteristics:
    type: array
    items: { $ref: ../resources/Characteristic.yaml }

  tiers:
    type: array
    items: { $ref: ../resources/Tier.yaml }

  catalogues:
    type: array
    items: { $ref: ../resources/Catalogue.yaml }

  group_hierarchy:
    description: Present only when `getGroupHierarchy=true`.
    nullable: true
    oneOf:
      - type: array
        items: { $ref: ../groups/Group.yaml }
      - type: object
        additionalProperties: true
required:
  - id
  - title
  - image
  - company
  - created
  - updated
  - characteristics
  - tiers
  - catalogues